name: Deploy to Server

on:
  push:
    branches:
      - explore-white-labeling # Replace with the branch you want to trigger the deployment

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com 
          "
          cd /path/to/your/app &&
          ./deploy.sh"